name: CheatBreakerAPI-Revision
version: 7f9b6de
description: Revisioned CheatBreakerAPI plugin
author: CheatBreaker Reimagined Development Team
website: https://oldcheatbreaker.com
main: com.cheatbreaker.api.CheatBreakerAPI
load: STARTUP
commands:
  isbanned:
  cheatbreaker:
    aliases: [cb]